---
- name: webserver
  yum:
    name: httpd
    state: present
- name: service start
  service:
    name: httpd
    state: started
    enabled: yes
- name: start service firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
- name: firewall rule
  firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: yes
- name: copy the content
  template:
    src: common.j2
    dest: /var/www/html/index.html

